version: '3.8'
services:
  web:
    build: .
    ports:
      - "3060:3060"
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=https://vgmfimjustgfznejbssv.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnbWZpbWp1c3RnZnpuZWpic3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDY4MTIsImV4cCI6MjA2NTkyMjgxMn0.hefa__m33bx2gW7fw20IxxKKfgY6WqVDWqgp8BSKKAw

      # Add any other env vars here, e.g. DATABASE_URL, NEXT_PUBLIC_SITE_URL, etc.
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env.local

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resumelm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
